// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    //AIzaSyClwB_BiurRd-g482j6CHrlAEr1dYLX10g
    apiKey: 'AIzaSyClwB_BiurRd-g482j6CHrlAEr1dYLX10g',
    appId: '1:700701375750:web:1c5d4c593147eaaee17287',
    messagingSenderId: '700701375750',
    projectId: 'trippo-4dc62',
    authDomain: 'trippo-4dc62.firebaseapp.com',
    databaseURL: 'https://trippo-4dc62-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-4dc62.appspot.com',
    measurementId: 'G-C7FLGJHEXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Zxtylmh-SvnulbzLzrzp_GuREhenLFQ',
    appId: '1:700701375750:android:c42bc5081c382552e17287',
    messagingSenderId: '700701375750',
    projectId: 'trippo-4dc62',
    databaseURL: 'https://trippo-4dc62-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-4dc62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iejQftGUCTMjMjB59VhmhbHvTkHjhT0',
    appId: '1:700701375750:ios:0a03f892e0743549e17287',
    messagingSenderId: '700701375750',
    projectId: 'trippo-4dc62',
    databaseURL: 'https://trippo-4dc62-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-4dc62.appspot.com',
    iosBundleId: 'com.trippoclone.drivers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iejQftGUCTMjMjB59VhmhbHvTkHjhT0',
    appId: '1:700701375750:ios:e0bc9a3c27921c2de17287',
    messagingSenderId: '700701375750',
    projectId: 'trippo-4dc62',
    databaseURL: 'https://trippo-4dc62-default-rtdb.firebaseio.com',
    storageBucket: 'trippo-4dc62.appspot.com',
    iosBundleId: 'com.trippoclone.drivers.RunnerTests',
  );
}
